"""add column qualification

Revision ID: 0915f53e0504
Revises: e7fc9ecf7fcc
Create Date: 2020-11-02 14:13:09.205625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0915f53e0504'
down_revision = 'e7fc9ecf7fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intern",
        sa.Column("qualification", sa.String(100))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intern", "qualification")
    # ### end Alembic commands ###
