"""create interns and assignment

Revision ID: e7fc9ecf7fcc
Revises: 
Create Date: 2020-11-02 13:46:28.806799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fc9ecf7fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'intern',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(50)),
        sa.Column('email', sa.String(50), unique=True, index=True),
        sa.Column('hashed_password', sa.String(500)),
        sa.Column('is_active', sa.Boolean, default=True)

    )
    op.create_table(
        'assignment',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('title', sa.String(100)),
        sa.Column('assigned_by', sa.String(50), unique=True, index=True),
        sa.Column('completed', sa.Boolean, default=False),
        sa.Column('owner_id', sa.Integer, sa.ForeignKey("intern.id"))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intern')
    op.drop_table('assignment')
    # ### end Alembic commands ###
